### ISSUE TITLE
smacks plugin does not work with node v4.0

### ISSUE THREAD

**Issue by vitalyster** [otalk/stanza.io#106]
Using echo client demo I got:
```
Error: Callback was already called.
    at C:\Users\Vitaly\Sources\stanza-demo\node_modules\stanza.io\node_modules\async\lib\async.js:43:36
    at C:\Users\Vitaly\Sources\stanza-demo\node_modules\stanza.io\node_modules\async\lib\async.js:694:17
    at C:\Users\Vitaly\Sources\stanza-demo\node_modules\stanza.io\node_modules\async\lib\async.js:173:37
    at Client.<anonymous> (C:\Users\Vitaly\Sources\stanza-demo\node_modules\stanza.io\lib\plugins\smacks.js:17:13)
    at Client.WildEmitter.emit (C:\Users\Vitaly\Sources\stanza-demo\node_modules\stanza.io\node_modules\wildemitter\wildemitter.js:108:30)
    at Client.<anonymous> (C:\Users\Vitaly\Sources\stanza-demo\node_modules\stanza.io\lib\client.js:70:14)
    at Client.WildEmitter.emit (C:\Users\Vitaly\Sources\stanza-demo\node_modules\stanza.io\node_modules\wildemitter\wildemitter.js:108:30)
    at WSConnection.<anonymous> (C:\Users\Vitaly\Sources\stanza-demo\node_modules\stanza.io\lib\client.js:291:18)
    at WSConnection.WildEmitter.emit (C:\Users\Vitaly\Sources\stanza-demo\node_modules\stanza.io\node_modules\wildemitter\wildemitter.js:120
:30)
    at WSConnection.<anonymous> (C:\Users\Vitaly\Sources\stanza-demo\node_modules\stanza.io\lib\transports\websocket.js:82:14)
    at WSConnection.WildEmitter.emit (C:\Users\Vitaly\Sources\stanza-demo\node_modules\stanza.io\node_modules\wildemitter\wildemitter.js:108
:30)
    at self.conn.onmessage (C:\Users\Vitaly\Sources\stanza-demo\node_modules\stanza.io\lib\transports\websocket.js:112:14)
    at EventTarget.dispatchEvent (C:\Users\Vitaly\Sources\stanza-demo\node_modules\stanza.io\node_modules\faye-websocket\lib\faye\websocket\
api\event_target.js:22:30)
    at instance._receiveMessage (C:\Users\Vitaly\Sources\stanza-demo\node_modules\stanza.io\node_modules\faye-websocket\lib\faye\websocket\a
pi.js:142:10)
    at null.<anonymous> (C:\Users\Vitaly\Sources\stanza-demo\node_modules\stanza.io\node_modules\faye-websocket\lib\faye\websocket\api.js:34
:49)
    at emitOne (events.js:82:20)
```

when `useStreamManagement: false` all works ok.

**Comment by ForNeVeR** [comment]
It seems that the problem is smacks plugin calling its callback multiple times.
