### ISSUE TITLE
While trying to build, error: make: *** [audit] Error 1

### ISSUE THREAD

**Issue by bersilius** [otalk/stanza.io#116]
Hello!

I have a fresh clone from github.
After npm install, I tried to run make.
Got this error:
...
nsp package
/...../node_modules/stanza.io/node_modules/nsp/node_modules/text-table/index.js:59
    return m ? m.index + 1 : c.length;
                              ^

TypeError: Cannot read property 'length' of undefined
    at dotindex (/...../node_modules/stanza.io/node_modules/nsp/node_modules/text-table/index.js:59:31)
    at /...../node_modules/stanza.io/node_modules/nsp/node_modules/text-table/index.js:11:21
    at Array.forEach (native)
    at forEach (/...../node_modules/stanza.io/node_modules/nsp/node_modules/text-table/index.js:73:31)
    at /...../node_modules/stanza.io/node_modules/nsp/node_modules/text-table/index.js:10:9
    at Array.reduce (native)
    at reduce (/...../node_modules/stanza.io/node_modules/nsp/node_modules/text-table/index.js:63:30)
    at module.exports (/...../node_modules/stanza.io/node_modules/nsp/node_modules/text-table/index.js:9:20)
    at prettyOutput (/...../node_modules/stanza.io/node_modules/nsp/lib/prettyOutput.js:32:17)
    at //...../node_modules/stanza.io/node_modules/nsp/commands/auditPackage/index.js:35:9
make: *** [audit] Error 1

Am I doing something wrong?

**Comment by legastero** [comment]
Nope, you did it right.

Looks like the optional auditing dependency has a broken version. I've removed it for now, so a git fetch should clear that up for you.

Thanks!

**Comment by bersilius** [comment]
It works for now.
Thanks for fast reply!
Very good library.
